pipeline {
	environment {
		registry = "http://128.131.58.67:5000" 
		registryCredential = 'dockerhub'
		dockerImage = ''
		dockerImage2 = ''

	}
	 
	agent any
	
	stages {
		stage('Build') {
			agent {
				docker {
					image 'maven:3-alpine'
					args '-u root'
				}
			}
			steps {
				sh 'mvn -B -DskipTests clean package'
				sh 'mvn test'
				sh './jenkins/scripts/deliver.sh'
				stash includes: 'target/my-app-1.0-SNAPSHOT.jar', name: 'ARTEFACT'
			}
		}
		stage('Build image') {
//			agent{ label 'puck' }
			agent{ label 'master' }
			steps {
				dir("ARTEFACT"){	
					unstash 'ARTEFACT'
				}
				script{
					docker.withRegistry(registry) {
						dockerImage = docker.build ("example")
					}
				}
			}	
	  	}
		stage('Push image to the registry') {
//			agent{ label 'puck' }
			agent{ label 'master' }
			steps{
				script{
					docker.withRegistry(registry) {
						dockerImage.push("${env.BUILD_NUMBER}")
						dockerImage.push("latest")
					}
				}
			}
		}
		stage('Pull image from the registry') {
//			agent{ label 'northstar' }
			agent{ label 'master' }
			steps{
				script{
					docker.withRegistry(registry) {
						dockerImage2 = docker.image("example:latest")
						dockerImage2.pull()
					}
				} 
			}
		}
		stage('Deploy the image'){
//			agent{ label 'northstar' }
			agent{ label 'master' }
			steps{
				sh 'pwd'
				sh 'ls'
				sh 'kubectl config view'
				sh 'kubectl apply -f myweb.yaml'
			}
		}
	}	
}
