pipeline {
	environment {
		registry = "https://hub.docker.com/"
		registryCredential = 'docker-hub'
		dockerImage = ''
	}
	
	agent none
	
	stages {
		stage('Build') {
			agent {
				docker {
					image 'maven:3-alpine'
					args '-u root'
				}
			}
			steps {
				sh 'mvn -B -DskipTests clean package'
				sh 'mvn test'
				sh './jenkins/scripts/deliver.sh'
				stash includes: 'target/my-app-1.0-SNAPSHOT.jar', name: 'ARTEFACT'
			}
		}
		stage('Build image') {
			agent{ label 'master' }
			steps {
				dir("ARTEFACT"){	
					unstash 'ARTEFACT'
				}
				sh "ls -la ${pwd()}"
				sh "ls -la ${pwd()}/ARTEFACT"
				script{
					dockerImage = docker.build registry + "jovan:1.0"				
				}
			}	
	  	}
		stage('Deploy image'){
			agent{ label 'master' }
			steps{
				script{
					docker.withRegistry('', registryCredential) {
						dockerImage.push()
					}
				}
			}
		}
	}	
}
